### ISSUE TITLE
Living Meeting players not unmuted

### ISSUE THREAD

**Issue by dwatring** [tanndev/silence-among-us#11]
## Bug Report
Testing the bot, and living players are still muted in the meeting state. Screenshot below shows the bot recognizes the meeting state, and that I'm living. It correctly mutes when the game begins, but does not unmute living once meetings begin.

### Steps to Reproduce
- (In game) Start a game
- Start a lobby
- Start & Link capture to lobby via DM link
- !sau meet to simulate meeting.

### Expected behavior
Expect living players to become unmuted.

### Screenshots
![image](https://user-images.githubusercontent.com/1572354/96157677-36337980-0ed8-11eb-9ea6-3244c40196e6.png)

**Comment by jftanner** [comment]
Thanks for the report! Let me take a look.

**Comment by jftanner** [comment]
I don't see any record of you in the logs, or in the player database. Are you using the public bot?
And, if so, can you send me your Discord ID so I can search the logs that way? (You'll need to [get it from Discord](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-).)

**Comment by jftanner** [comment]
(Closing as resolved, but feel free to post if you have any questions.)

**Comment by dwatring** [comment]
Oh, perfect. apologies. I thought it was automatically joining, but that's just the status of the capture.

**Comment by jftanner** [comment]
No worries! Just means I need to polish up the interface a bit to make it less confusing. :)

Thanks for opening a ticket, and feel free to do so again if you encounter any bugs or problems.
