### ISSUE TITLE
404 Error: Not Found

### ISSUE THREAD

**Issue by Thebirdman567** [tanndev/silence-among-us#12]
## Bug Report
Any command I enter results in a 404 error

### Steps to Reproduce
Enter and command, you'll probably get this error

### Expected behavior
I expected the command do run, such as stopping a lobby with !s stop or joining a lobby with !sj

**Comment by jftanner** [comment]
Just as an FYI, you're not supposed to put your answers _in_ the comments. Otherwise nobody can read them. :)

Let me take a look at the logs and see what's there.

**Comment by jftanner** [comment]
There's definitely some weirdness going on in the server. I see all the 404s, but I'm not sure what's causing them. Restarting the bot seems like maybe it fixed it. But I'll need to investigate further when I get a chance next week.

**Comment by jftanner** [comment]
I haven't seen any more evidence of this, so I'm going to go ahead and close the issue.
