### ISSUE TITLE
Bot ends lobbies for inactivity during active games

### ISSUE THREAD

**Issue by imperri** [tanndev/silence-among-us#16]
## Bug Report
The bot will end a lobby stating "Nothing has happened 30 minutes, so I ended the lobby." despite the lobby being actively in use for a game. Bot automatically unmutes everyone when it occurs, proceeds to mute everyone as per usual after a state change in the game. Attempting to use "!sau stop" to close the lobby after this bug appears has the bot say "There's not a lobby for your voice channel. Try !sau start!"

### Steps to Reproduce
Play games with the bot running alongside Among Us Capture.
Eventually (Feels like it might be around the 30 minute mark but not confirmed) bot will claim to close the lobby.

### Expected behavior
Bot should detect the game as still running and not end lobby

### Screenshots
https://imgur.com/a/350CUOK

**Comment by jftanner** [comment]
I think the 30 minute limit is too short. I'll double it in the next version.

But are you saying that it still responds to game commands after it's supposedly ended the lobby for inactivity?

Also, are you using AmongUsCapture, or running it manually?

**Comment by imperri** [comment]
I'm using it alongside AmongUsCapture, and when AmongUsCapture updates the
game state (going from in meeting back to in game for example) the bot
reacts correctly.

It seems like the bot ends the lobby and unmutes all players, but still
handles muting and unmuting correctly once the game state changes. I
haven't tested to see if it would respond to manual commands once it ends
the lobby, but trying to issue a command to stop the lobby doesn't work,
which made making new lobbies a little weird.

I'm not sure that the time limit is too short, as we never had a 30 minute
period where nothing at all happened. The only time the limit came to our
attention was when it was killing the lobby mid game.

**Comment by jftanner** [comment]
Hrm. Any updates from the capture should be resetting the 30-minute timer as well.

What's even more strange is that it can still manage the lobby after it's stopped. The lobby shouldn't even exist anymore for it to be updating it. But it would seem that it's only half deleted.

I've noticed some other strange behavior too, so I think I need to re-evaluate how lobbies are stored, loaded, and updated. (Unfortunately, I wasn't able to replicate this myself. My group played for several hours without encountering it.)

**Comment by BaDy17** [comment]
I have the same problem, after 30 minutes, the bot stop the lobby but unmute mute, when the game still running.

I think the bot don't reset the timer when we use AmongUsCapture

**Comment by BaDy17** [comment]
![image](https://user-images.githubusercontent.com/69623379/96912024-fbb27980-14a1-11eb-81c5-f2efc80dc7db.png)

**Comment by jftanner** [comment]
> I think the bot don't reset the timer when we use AmongUsCapture

It's weirder than that. Because the lobby shouldn't still _work_ after it's been timed out. It shouldn't be accepting updates from the bot either.

**Comment by BaDy17** [comment]
I know that and if I try !sau stop it answers "There"s not a lobby..."

If I continue to play another game the bot continues to close the lobby again after a certain time.

And again and again. I can't "stop" and if I start a new lobby I have the same situation after some minutes.

It's like the bot stacks the same lobby after updates (dead, emergencycall, etc) and close all lobbys after x time

**Comment by jftanner** [comment]
So far, I've confirmed a couple things:
- The lobby IS destroyed by the timeout. (So that needs to be longer.)
- Destroyed lobbies are removed from `lobbiesByVoiceChannel` and the backup database.
- Destroyed lobbies are _not_ removed from `lobbiesByConnectCode`, because the socket is still able to update it.

For example, this is what happens if I let my lobby timeout and then change my color:
![image](https://user-images.githubusercontent.com/10095474/96933668-e3852f00-148e-11eb-9915-fc3e172e3360.png)

**Comment by imperri** [comment]
Heads up, seems like it hasn't been fully resolved as we just had it happen again in our game.

https://imgur.com/a/j4EUbvT

**Comment by jftanner** [comment]
Hrm. Can you use `!sau version` for me?

(FYI: you can paste images directly into Github comments. No need for Imgur.)

**Comment by imperri** [comment]
Oh, didn't even realise I could directly comment a photo.
The bot reports version 2.5.2

**Comment by jftanner** [comment]
I've had two lobbies running in parallel for the last 5+ hours, with no issues. Are you _sure_ this is still occurring?

(I _did_ recently fix a bug in which a stopped lobby would post in Discord that it had timed out, about an hour after it was stopped.)

**Comment by imperri** [comment]
Unless somewhere in between 2.3.0 and now you've fixed this issue again, it definitely still occurs.

That last screenshot I sent shows the bot ending the lobby, the bot updating the same lobby moments later and then me trying to use '!sau lobby' to double check if the same issue occurred. The exact same behaviour showed up as before the first fix. 

For what it's worth, we were playing for about 5 hours last night and had the issue pop up twice, which is significantly less frequent than it was happening before

**Comment by jftanner** [comment]
I'm still not able to replicate this at all, unfortunately.

If you encounter it again, can you give me an exact (as possible) time when it happened? (Make sure to include a timezone).
I'll also need your Discord [server ID](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-).

**Comment by imperri** [comment]
Sure can. I havent actually had a chance to play since it last popped up, but if I encounter it again I'll give you all the info I can.
