### ISSUE TITLE
New players cannot join the lobby

### ISSUE THREAD

**Issue by sakerinha** [tanndev/silence-among-us#17]
## Bug Report

Hi! Not sure this is a bug or a config, but whenever we play a match (e.g. with 5~6 people) and someone else tries to join the lobby, he receive the message "<name>, Guild member (undefined isn't in the lobby."
Also, we noticed that this issue may also happen if some minutes (didn't checked how many) have passed after the start of the lobby (I think it was around 10m)

### Steps to Reproduce

1- Play a game with fewer people
2- once the match is over, ask to someone else join the lobby

### Expected behavior

Let anyone join the lobby if the status is "intermission"

**Comment by jftanner** [comment]
From your description, I think you've encountered a bug I found the other day.

When someone joins the voice channel during a lobby, they should be automatically added as a spectator. (And listed at the bottom of the info post.) But that doesn't always happen for some reason.

I'm going to fix that as soon as I can, but there's a workaround: if someone doesn't show up as a spectator, have them switch to a different voice channel for a couple seconds and then switch back. That gives the bot a chance to see them again.

**Comment by sakerinha** [comment]
Oh, thanks for the tip. Gonna try that next time we play.

**Comment by BaDy17** [comment]
I have the same problem, if the game is running, new ppl can join the vocal but the bot don't but them in spectator ... So to fix that I stop and restart a lobby.
