### ISSUE TITLE
Admin command to join or kick from lobby

### ISSUE THREAD

**Issue by sakerinha** [tanndev/silence-among-us#18]
## Feature

Admin command to let others (or just the admins and moderators from the discord server) to force join the spectators into the lobby, and have a command to kick a person from the lobby if he's not in the voice channel (and not in the match) anymore.

### Reasons for Implementing

For the force join command, the idea is to let someone with higher permissions to force others join the lobby, most to prevent someone from not joining, and also helping those who are playing using the mobile discord and mobile among us.
As for the kick command, I've noticed that if the person who is leaving the match doesn't use the command to leave the lobby, it will stay in there. Also, the same reason for the mobile players.

I guess this will help to manage the lobby a lot more easier.
Thanks in advance.

**Comment by jftanner** [comment]
I've considered a force join. I think that's a good idea.

Fortunately, there's already the `!sau eject @mention` to kick people out. :)

(I haven't done permissions at all yet. It's on the todo list.)

**Comment by sakerinha** [comment]
I did saw the "eject" in the commands folder, but it was after I posted :v hahaha
I guess it would be nice to mention the command in the help menu, haven't found it there.
Also, regarding the commands, it would also be nice to have a list of what settings we can change using the config command, and an exemple of usage.
Many thanks mate! It's a preeeeetty nice job you're doing here

**Comment by jftanner** [comment]
Huh... `eject` isn't in the help text. Interesting. [I'll fix that](https://github.com/tanndev/silence-among-us/issues/19).

For the `config` command, currently there's only a `prefix` option. (Kinda, mostly, almost, documented [in the readme](https://github.com/tanndev/silence-among-us/issues/19).) But you're right, that command needs better docs.

And thanks! I'm glad the bot is working out for you. :) Thanks so much for all your feedback. It's super helpful.

**Comment by jftanner** [comment]
I've been thinking about this a bit more, and I don't think I can add a "force-join" command, since it would require allowing one player to alter the database record of another player. I might be able to solve that later, but it won't be near-term.

I've gone ahead and added an example for the `config` command, though, and added the missing `eject` command to the help. Those will both be in the next version. (It's tagged, so you'll see an update here.)
