### ISSUE TITLE
Changing prefix into a single character making the bot unusable

### ISSUE THREAD

**Issue by awang-karisma** [tanndev/silence-among-us#27]
## Bug Report
Hello, i recently added the bot to my server and trying to change the prefix.
I changed the prefix to dollar sign "$", and then the bot isn't picking any command i typed. 
I confirmed it by typing "!say-rollcall" and it is indeed the bot already changed the prefix to "$", but the bot just don't reply to any command i issue, like "$ help" etc

### Steps to Reproduce
- Change the prefix to "$" 
`!sau config set prefix $`
- Check if bot is using the new prefix
`!sau-rollcall`
`Silence Among Us: @User, I'm listening for $
Try using $ help for more information.`
- Try any command with the new prefix, bot won't response
`$ help`

### Expected Behavior
Bot listens to the new prefix

**Comment by jftanner** [comment]
Ah, I know the problem. That's a special character in regular expressions and I'm not escaping it properly. I'll get that fixed.
