### ISSUE TITLE
Auto Join by Profile

### ISSUE THREAD

**Issue by DirtyCajunRice** [tanndev/silence-among-us#33]
## Feature

When a new game is created, associate players in game with existing users.

### Reasons for Implementing

It is tedious to have users type join every time you choose to change a map.
### Ideas & Details

The server has its list of saved users, and their names. If it is initialized or a player joins, and their discord name matches their saved profile, then automatically add them to the game
### Alternatives

Not an alternative, but potentially added as an opt-in initially and then switched to default if so desired

**Comment by jftanner** [comment]
I'm not sure what you mean.

Players only need to join once. If the host exits the game and starts a new one (say, go change the map), the Discord-linked players will be preserved. 

The only time you need to use `join` is when you start playing, or if you need to change your in-game name.

Although... Auto-joining players based on their cached name is an interesting idea. I wish there was something more unique than in-game name to use for that, but c'est la vie.

**Comment by DirtyCajunRice** [comment]
I may have conflated the new game needing to reinitialize with some other test last night. Was a but late haha but yes the auto join in general would be nifty 😃

**Comment by jftanner** [comment]
@DirtyCajunRice Thank you for this idea.

Very exciting comment in 3... 2.... 1......

**Comment by jftanner** [comment]
*sigh* I hadn't noticed [that bug](https://github.com/tanndev/silence-among-us/issues/36) before.

Here's an [actual link](https://github.com/tanndev/silence-among-us/releases/tag/v2.6.0-beta.5).

**Comment by DirtyCajunRice** [comment]
saw that in the last beta link and just assumed you were placeholder-ing it. Deployed and will test this evening!
