### ISSUE TITLE
Presence Customization

### ISSUE THREAD

**Issue by DirtyCajunRice** [tanndev/silence-among-us#34]
## Feature

Customizable Presence text.
### Reasons for Implementing

Currently, the bot is hardcoded to !sau-rollcall which is already misleading if you have changed prefix.
### Ideas & Details

The de-facto standard for these types of bots has trended toward 
```
${prefix} help | Watching ${num} games in ${num} servers
```
Personally, I think the help is too verbose and everything to the right of the pipe is perfect, but opinions are endless haha. Possibly above as the default for MVP with roadmap to user customizable text?

### Alternatives

At a minimum, the ability to completely replace the status text as is, via
```
!sau config set status crewmates get bamboozled
```
assuming stull hardcoded watching prefix.

**Comment by jftanner** [comment]
I'm under the impression that presence is a global setting and can't be changed per-guild. Am I wrong about that?

**Comment by DirtyCajunRice** [comment]
Yes it is global which is why i personally am not a fan of the prefix info in it at all and think it should be left to the right of the pipe info-wise

**Comment by jftanner** [comment]
Any instance of the bot will respond to that command and say what it's current prefix is.

And it can't be customizable, then, because the bot is in multiple guilds.

**Comment by jftanner** [comment]
To clarify: ` !sau-rollcall` is _not_ a guild-specific command prefix. Every bot responds to it, no matter what you've changed your prefix to.

**Comment by DirtyCajunRice** [comment]
@jftanner  this is not a per guild request, this is a request for a bot owner to be able to change it globally

**Comment by jftanner** [comment]
Ah. You're talking about a self-hosted bot.

I don't currently have any plans to provide additional functionality for self-hosting. This project is time consuming enough just trying to focus on the "official" bot.

If you're interested in forking your own version to make that sort of change, the presence setting is here: https://github.com/tanndev/silence-among-us/blob/main/discord-bot/discord-bot.js#L23

**Comment by DirtyCajunRice** [comment]
I cant imagine there being many other self-hosted only options to implement out there! For clarity, if i make an MR is it something you are just not willing to do yourself or is it something you do not want as part of the project? Im a golang/python guy but I can do an mr for this if its the latter.

**Comment by jftanner** [comment]
The presence text is set statically right now, so there's no mechanism to dynamically update that with lobby/guild counts or anything like that. Adding a mechanism for that, which is customizable, is complexity I don't want to introduce. (You'd need to have some kind of templating system which hooks into other parts of code to identify when changes are made.) So, that's not a PR I'd accept.

If, however, you want to customize the _static_ text with an environment variable... well, I can add that right now. :D

**Comment by DirtyCajunRice** [comment]
I will take it! there is no _need_ for it to be a command and an env var will do exactly the same thing. I greatly appreciate it!

**Comment by jftanner** [comment]
Give that linked commit a gander. (It'll be in the beta release shortly.)

**Comment by DirtyCajunRice** [comment]
Tested and validated with both presence name and type! Also can validate that prefix in the scheduledInfo message now reflects a custom prefix. Thanks jftanner!

**Comment by jftanner** [comment]
Very welcome!

**Comment by DirtyCajunRice** [comment]
@jftanner heads up - bot link is still sus :)
