### ISSUE TITLE
v2.6.0 shows unreleased in version call

### ISSUE THREAD

**Issue by dirtycajunrice** [tanndev/silence-among-us#40]
## Bug Report

Version call shows unreleased
### Steps to Reproduce

```
!sau v
```
### Screenshots

![example](https://images.cajun.pro/7ac5b/huWuMavO61.png/raw)

**Comment by jftanner** [comment]
![image](https://user-images.githubusercontent.com/10095474/97741114-a507f980-1ab8-11eb-853d-818813541bdd.png)
