### ISSUE TITLE
Configurable spectator behavior

### ISSUE THREAD

**Issue by jftanner** [TannDev/silence-among-us#43]
## Feature
From #41:
> Make [spectator handling] configurable. (I'm thinking mute, ignore dead for settings, with a warning that the last option will impact performance.)

### Reasons for Implementing
Some users want spectators to be ignored, other users want them to be muted. whynotboth.gif

### Ideas & Details
Add a new `spectators` config options with three values:
- `mute`: Spectators are muted during the game.
- `ignore`: Spectators are ignored entirely.
- `dynamic`: Spectators are muted/unmuted dynamically along with dead people.

**Comment by jftanner** [comment]
CC @douglasmonsky

**Comment by douglasmonsky** [comment]
Adding back the ability to ignore spectators will make my server very happy, appreciate that it is on your to-do list!

**Comment by jftanner** [comment]
I think there might be some problems with the `spectators: ignore` option. Namely, it's possible that the bot will fail to unmute people at the end of the game, if they become spectators automatically.

Unfortunately, I can't test it properly because my personal Discord server is having some pretty severe lag issues. So it's on the beta branch for now, and I'll test it more when I have the chance.

**Comment by jftanner** [comment]
Closing this issue because the project will be shuttered soon. See #63.
