### ISSUE TITLE
Not working with new patch

### ISSUE THREAD

**Issue by douglasmonsky** [tanndev/silence-among-us#44]
I'm guessing you already know, but my bot has stopped working on the main version of the game with the new update they just pushed.

**Comment by jftanner** [comment]
I've been out of the loop this evening. I'll check it out in the morning.

However, the AmongUsCapture devs will put out a new version quickly, if they haven't already. Should just be a matter of upgrading.

**Comment by vrnagy** [comment]
The new AmongUsCapture (2.4.2) works perfectly for us

**Comment by douglasmonsky** [comment]
> The new AmongUsCapture (2.4.2) works perfectly for us

Yup, I was able to get it working again by downloading the exe from [ here ](https://github.com/denverquane/amonguscapture/releases/tag/2.4.2)

**Comment by jftanner** [comment]
Excellent. I'll put an updated link in the bot as soon as I get a chance.

Also a super easy first issue, for anyone interested in making a PR. :)
