### ISSUE TITLE
[Feature Request] Voice channel moving

### ISSUE THREAD

**Issue by ablomer** [TannDev/silence-among-us#46]
Option to move users to a different voice channel, instead of muting and deafening them, to allow dead players to communicate.

**Comment by jftanner** [comment]
Can you explain your intended use case in a bit more detail?

Dead players can already talk during the working phase, so are you just looking to have them _also_ talk during meetings?

**Comment by ablomer** [comment]
Right, the idea is to prevent dead players from getting cut-off if they are talking and a meeting begins.

**Comment by jftanner** [comment]
If I do that, then they won't be able to hear the living members discussing. It's a personal opinion, but that feels like it defeats a lot of the fun.

I'll keep the issue open for future consideration, or if somebody decides to do a PR, but I'm not going to put it on my immediate roadmap to implement myself.

In the meantime, users can always switch channels whenever they like. The bot will automatically unmute them when they leave the managed channel.

**Comment by jftanner** [comment]
Closing this issue because this project will be shuttered soon. See #63.
