### ISSUE TITLE
[Bug] Players who are not joined appear twice in the players list

### ISSUE THREAD

**Issue by ablomer** [TannDev/silence-among-us#47]
## Bug Report
Players who are not joined appear twice in the players list

### Steps to Reproduce
1. Start a game with Among Us Capture connected (`!sau start`)
2. All players who are in the Discord voice channel join the lobby (`!sau join <name>`)
3. Players who are not joined will appear twice in the list

### Expected behavior
All players should be listed once

### Screenshots
```
Players (12)
:stopwatch: @Guto (guto) (Orange)
:stopwatch: @Sabi~ (SabiSus) (Blue)
:stopwatch: @Los (Dr Los) (Cyan)
:stopwatch: Jakt Noob (Red)
:stopwatch: Jakt Noob (Blue)
:stopwatch: @Juice (Dr Rho) (Green)
:stopwatch: MikeHunt (White)
:stopwatch: MikeHunt (White)
:stopwatch: Not Ghandi (Black)
:stopwatch: Not Ghandi (Black)
:stopwatch: Eiei (Lime)
:stopwatch: Eiei (Lime)
```
In the above sample, _Jakt Noob_, _MikeHunt_, _Not Ghandi_, and _Eiei_ are listed twice

**Comment by jftanner** [comment]
Hrm. What a strange bug.

I'll definitely investigate. Thank you.

**Comment by AlexandreChasseteau** [comment]
I noticed the same, plz fix it if you can :p

**Comment by BaDy17** [comment]
I have the same bug.

![image](https://user-images.githubusercontent.com/69623379/98872626-3000d080-2477-11eb-877e-c698917ff0ba.png)

**Comment by jftanner** [comment]
What's particularly interesting about that is it's _not_ just the captured players. There's duplicates for (almost) everyone.

Sorry I haven't had time to look into this. I've been swamped recently.

**Comment by DirtyCajunRice** [comment]
![image](https://images.cajun.pro/7ac5b/voHiceYO69.png/raw)

Once they join they stay as well. (if that helps narrow it down)

**Comment by 4anthony6** [comment]
Just some question to (maybe) help solving it : 

Did you all tried to install it manually with the Discord Developer Portal before trying to install it via the private messages of the bot?

Did you all have created a file with the token of the bot?

**Comment by jftanner** [comment]
This occurs with the official, hosted version.

**Comment by jftanner** [comment]
I never did get a chance to get to the bottom of this.
But now this project will be shuttered soon. See #63.
