### ISSUE TITLE
Bot doesn't respond to !sau

### ISSUE THREAD

**Issue by BaDy17** [tanndev/silence-among-us#51]
## Bug Report
Bot doesn't respond to !sau

### Steps to Reproduce
Just tried !sau start or !sau help

### Expected behavior
Nothing happend

### Screenshots
-

**Comment by jftanner** [comment]
I need more information.

What server is it in?
Have you tried `!sau-rollcall`?

**Comment by BaDy17** [comment]
I eject the bot and reinvite.

It's working again.
