### ISSUE TITLE
Emojis to join

### ISSUE THREAD

**Issue by maddenfederico** [TannDev/silence-among-us#52]
## Feature
Allow players to connect to the game using emojis, like with AmongUsCapture
### Reasons for Implementing
My friends are lazy and don't want to type things

**Comment by jftanner** [comment]
Hrm, alright, let's explore this idea a bit!

With auto-join, the only time a player needs to use `join` is set a new/different in-game name. This information is necessary for the bot's function and can't be skipped.

So, what might this look like? Maybe we could assign a number to each unlinked player from capture, and then make those numbers available as reactions.

**Comment by vrnagy** [comment]
I made a version of this for our team.
When an unknown user is present, the bot writes a message to the text channel "Hello ${name}, please react to this message", and when the user reacts to it, the bot assigns the player like one used the join command

**Comment by jftanner** [comment]
Ooh, that's a neat idea!

**Comment by vrnagy** [comment]
If You like I can make a PR from it

**Comment by jftanner** [comment]
That's alright. I'll play around with it. :)

(With the election stuff, I haven't touched any of this code in a week. But I'm hoping that changes soon.)

**Comment by jftanner** [comment]
Sadly, that did not change. An this project will be shuttered soon. See #63
