### ISSUE TITLE
[Feature Request] Assign multiple in game players to 1 Discord user

### ISSUE THREAD

**Issue by WonderfulSpivey** [tanndev/silence-among-us#58]
The group I play with regularly has multiple married couples that play together in the same room using 1 Microphone and 1 Discord account for both of them, is it possible to add the ability to assign multiple players to 1 discord account and treat the discord account as alive unless both players are dead?

**Comment by jftanner** [comment]
Unfortunately, this would require a major architectural change under the covers.
